blog/urls.py
from django.urls import path
from blog import views
app_name='blog'
urlpatterns=[
    path('',views.PostList.as_view(),name='post_list'),
    path('page/<int:page>/',views.PostList.as_view(),name='home'),
    path('postdetail/<slug:slug>',views.PostDetail.as_view(),name='post_detail'),
    path('category/<slug:slug>',views.category,name='category'),
    path('category/<slug:slug>/page/<int:page>',views.category,name='category')
]

login/urls.py
from django.urls import path
app_name='login'
urlpatterns=[

]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',include('login.urls',namespace='login')),
    path('shop/',include('shop.urls',namespace='shop')),
    path('blog/',include('blog.urls',namespace='blog')),
    path('videos/',include('videos.urls',namespace='videos')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.urls import path

app_name = 'shop'
urlpatterns = [

]

videos/urls.py
from django.urls import path

app_name = 'videos'
urlpatterns = [

]

blog/models.py
from django.db import models
from login.models import CustomUser
from django.urls import reverse
from django.utils import timezone
from extensions.utils import jalali_converter


# Create your models here.
class CategoryManage(models.Manager):
    def active(self):
        return self.filter(status=True)


class Categoty(models.Model):
    parent = models.ForeignKey('self',default=None,null=True,blank=True,on_delete=models.SET_NULL,related_name='child',verbose_name='عبارت زیر دسته')
    name = models.CharField(max_length=20, verbose_name="نام")
    slug = models.SlugField(unique=True, max_length=100, verbose_name="لینک کوتاه")
    status = models.BooleanField(default=True, verbose_name="آیا نمایش داده شود")
    position = models.IntegerField(verbose_name='پوزیشن')

    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"
        ordering = ['parent__id','position' ]

    def __str__(self):
        return self.name




# class PostManager(models.Manager):
# def get_queryset(self):
#   return super(PostManager,self).get_queryset().filter(status="published")


class PostManage(models.Manager):
    def published(self):
        return self.filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'در حال انتظار'),
        ('published', 'منتشر شده'),
    )
    name = models.CharField(max_length=50, verbose_name="نام")
    slug = models.SlugField(unique=True, max_length=100, verbose_name="لینک کوتاه")
    category = models.ManyToManyField(Categoty, verbose_name="دسته بندی", related_name="posts")
    image = models.ImageField(upload_to='media', verbose_name="تصویر")
    subtitle = models.CharField(max_length=800, verbose_name="توضیحات")
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='blog_post', verbose_name="نویسنده")
    body = models.TextField(verbose_name="متن اصلی")
    publish = models.DateTimeField(default=timezone.now, verbose_name="تاریخ انتشار")
    created = models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد")
    updated = models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی")
    status = models.CharField(max_length=25, choices=STATUS_CHOICES, default='draft', verbose_name="وضعیت انتشار")
    objects = PostManage()

    class Meta:
        verbose_name = "مقاله"
        verbose_name_plural = "مقالات"
        ordering = ('-publish',)

    def __str__(self):
        return self.name



    def jpublish(self):
        return jalali_converter(self.publish)

    jpublish.shor_description = "زمان انتشار"

    def category_published(self):
        return self.category.filter(status=True)

login/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _

from .managers import UserManager


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return self.email

shop/models.py
from django.db import models

# Create your models here.

videos/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from .models import Post, Categoty
from django.views.generic import ListView,DetailView

# Create your views here.


class PostList(ListView):
    queryset = Post.objects.published()
    paginate_by = 2

class PostDetail(DetailView):
    def get_object(self):
        slug = self.kwargs.get('slug')
        return get_object_or_404(Post.objects.published(),slug=slug)

def postdetail(request, year, month, day, post):
    post = get_object_or_404(Post, publish__year=year, publish__month=month, publish__day=day, slug=post)
    return render(request, 'blog/post_detail.html', {"post": post})


def category(request, slug,page=1):
    category = get_object_or_404(Categoty, slug=slug, status=True)
    post_list = category.posts.published()
    paginator = Paginator(post_list, 3)
    post = paginator.get_page(page)
    return render(request, "blog/category.html", {"category": category,'post':post})

login/views.py
from django.shortcuts import render

# Create your views here.

shop/views.py
from django.shortcuts import render

# Create your views here.

videos/views.py
from django.shortcuts import render

# Create your views here.

templates/blog/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post_detail.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2021</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

templates/blog/base.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>وبسایت من{% block title %}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href=" static/blog/assets/img/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'blog/css/styles.css' %} " rel="stylesheet" />
        <link href="{% static 'blog/css/rtl.css' %} " rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'blog:post_list' %}">{% title %}</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    منو
                    <i class="fas fa-bars"></i>
                </button>
               {% category_navbar %}
            </div>
        </nav>
        <!-- Page Header-->

        <!-- Main Content-->
       {% block main %}
        {% endblock %}
                    <!-- Divider-->

        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>

                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">وبلاگ شخصی من </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'blog/js/scripts.js' %}"></script>
    </body>
</html>

templates/blog/category.html
{% extends 'blog/base.html' %}
{% load static %}
        {% block main %}

             <header class="masthead" style="background-image: url({% static 'blog/assets/img/IMG_20180616_003349_664.jpg'%})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>ابیروگرام</h1>
                            <span class="subheading">.به وبسایت چند منظوره من خوش اومدید</span>
                            <span class="subheading">...فروشگاه اینترنتی، آپلود سنتر ویدیو و یه وبلاگ با کلی مقاله مفید</span>

                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <div class="container">
            <div class="row">
                <div class="col-md-10 col-lg-8 mx-auto">
                <h3 class="alert alert-primary text-center">  دسته بندی: {{ category.name }} </h3>
                    <!-- Post preview-->
                   {% for post in post %}
                        <div class="post-preview">
                        <a href="post_detail.html">
                            <h2 class="post-title"><a href="{{ post.get_absolute_url }}">{{ post.name }}</a></h2>
                            <h3 class="post-subtitle">{{ post.subtitle | truncatewords:20 }}</h3>
                        </a>
                        <p class="post-meta">
                            مقاله از
                            <a href="">{{ post.author }}</a>
                            {{ post.jpublish }}
                        </p>

                        <div>
                            {% for categoris in post.category_published.all %}
                                <a href="#">#{{ categoris.name }}</a>
                            {% endfor %}
                        </div>
                    </div>
                    {% endfor %}
                    <!-- Divider-->
                    <hr class="my-4" />
                    <!-- Post preview-->

                    <!-- Divider-->

                    <!-- Pager-->
                 <div  class="clearfix pager-botton">
                        {% if page_obj.has_previous %}
                            <a class="btn btn-primary float-right ml-3" href="{% url 'blog:category' category.slug page_obj.previous_page_number %}" >پست های جدید تر</a>
                        {% endif %}
                        {% if page_obj.has_next %}
                            <a class="btn btn-primary float-right ml-3" href="{% url 'blog:category' category.slug page_obj.next_page_number %}" >پست های قدیمی تر</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}

templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %} | {{ post.name }}{% endblock %}
{% block main %}
     <header class="masthead" style="background-image: url('{{ post.image.url }}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading ">
                            <h1>{{ post.name }}</h1>
                            <h3 class="subheading">{{ post.subtitle }}</h3>
                            <time>{{ post.jpublish }}</time>
                        </div>
                    </div>
                </div>
            </div>
        </header>
    <article>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-10 mx-auto text-justify">
                        {{ post.body | linebreaks }}
                            گردآوری توسط
                            <a href="">{{ post.author }}</a>
                            منتشر شده در تاریخ
                            <small>{{ post.jpublish }}</small>

                    </div>
                </div>
            </div>
        </article>
{% endblock %}

templates/blog/partials/category_loop.html
<ul class="navbar-nav ml-auto">
    {% for categoris in categoris.child.active %}
        <li class="nav-item">
            <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:category' categoris.slug %}">{{ categoris.name }}</a>
        {% if categoris.child.active %}
                  {% include 'blog/partials/category_loop.html' %}
        {% endif %}
        </li>
    {% endfor %}
</ul>

templates/blog/partials/category_navbar.html
<div class="collapse navbar-collapse nav" id="navbarResponsive">
    <ul class="navbar-nav ms-auto py-4 py-lg-0">
        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:post_list' %}">خانه</a></li>
        {% for categoris in categoris %}
            {% if categoris.parent == None %}
                <li class="nav-item">
                    <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:category' categoris.slug %}">
                        {{ categoris.name }}
                    </a>
                </li>
                {% if categoris.child.active %}
                    {% include 'blog/partials/category_loop.html' %}
                {% endif %}
            {% endif %}
        {% endfor %}
    </ul>
</div>

templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %} | {{ post.name }}{% endblock %}
{% block main %}
     <header class="masthead" style="background-image: url('{{ post.image.url }}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading ">
                            <h1>{{ post.name }}</h1>
                            <h3 class="subheading">{{ post.subtitle }}</h3>
                            <time>{{ post.jpublish }}</time>
                        </div>
                    </div>
                </div>
            </div>
        </header>
    <article>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-10 mx-auto text-justify">
                        {{ post.body | linebreaks }}
                            گردآوری توسط
                            <a href="">{{ post.author }}</a>
                            منتشر شده در تاریخ
                            <small>{{ post.jpublish }}</small>

                    </div>
                </div>
            </div>
        </article>
{% endblock %}

templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% load static %}
        {% block main %}
             <header class="masthead" style="background-image: url({% static 'blog/assets/img/IMG_20180616_003349_664.jpg'%})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>ابیروگرام</h1>
                            <span class="subheading">.به وبسایت چند منظوره من خوش اومدید</span>
                            <span class="subheading">...فروشگاه اینترنتی، آپلود سنتر ویدیو و یه وبلاگ با کلی مقاله مفید</span>

                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Post preview-->

                   {% for posts in object_list %}
                        <hr class="my-4" />
                        <div class="post-preview">
                        <a href="post_detail.html">
                            <h2 class="post-title"><a href="{% url 'blog:post_detail' posts.slug %}">{{ posts.name }}</a></h2>
                            <h3 class="post-subtitle">{{ posts.subtitle | truncatewords:20 }}</h3>
                        </a>
                        <p class="post-meta">
                            مقاله از
                            <a href="">{{ posts.author }}</a>
                            {{ posts.jpublish }}
                        </p>

                        <div>
                            {% for categoris in posts.category_published.all %}
                                <a href="{% url 'blog:category' categoris.slug %}">#{{ categoris.name }}</a>
                            {% endfor %}
                        </div>
                    </div>
                       <hr class="my-4" />
                    {% endfor %}
                    <!-- Divider-->

                    <!-- Post preview-->

                    <!-- Divider-->

                    <!-- Pager-->
                    <div  class="clearfix pager-botton">
                        {% if page_obj.has_previous %}
                            <a class="btn btn-primary float-right ml-3" href="{% url 'blog:home'  page_obj.previous_page_number %}" >پست های جدید تر</a>
                        {% endif %}
                        {% if page_obj.has_next %}
                            <a class="btn btn-primary float-right ml-3" href="{% url 'blog:home' page_obj.next_page_number %}" >پست های قدیمی تر</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}